services:
  apigateway:
    container_name: apigateway
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      DOTNET_AUTH_SERVICE_IP: "${DOTNET_AUTH_SERVICE_IP}"
      DOTNET_PAYMENT_SERVICE_IP: "${DOTNET_PAYMENT_SERVICE_IP}"
      JAVA_SERVICE_CHAT_AI_IP: "${JAVA_SERVICE_CHAT_AI_IP}"
      JAVA_SERVICE_PANEL_IP: "${JAVA_SERVICE_PANEL_IP}"
      JAVA_SERVICE_TEST_IP: "${JAVA_SERVICE_TEST_IP}"
      JAVA_SERVICE_UNIVERSITIES_IP: "${JAVA_SERVICE_UNIVERSITIES_IP}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
